### ISSUE TITLE
Bandit image?

### ISSUE THREAD

**Issue by pzelnip** [cytopia/docker-pylint#7]
Wasn't sure where to file this, but I love these Docker images for CI.  It would be great if there was one for the `Bandit` tool: https://pypi.org/project/bandit/

I'd be happy to collaborate on one if interested.

**Comment by cytopia** [comment]
@pzelnip let me know how that works for you: https://github.com/cytopia/docker-bandit

**Comment by pzelnip** [comment]
You are awesome, thank you so much.  Works perfectly.
